INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('52',' ','Policy Issuance Workflow','System')
,('1','Complete','Manual Data Entry','NB_DE')
,('2','Manual Entry','Manual Data Entry','NB_DE')
,('3','Hold','Manual Data Entry','NB_DE')
,('4','Complete','Check Data Completeness','System')
,('5','Not Complete','Check Data Completeness','System')
,('6','Complete','Check Duplicate Proposal in LAS & BPM','System')
,('7','Not Complete','Check Duplicate Proposal in LAS & BPM','System')
,('8','Reindex CM','Exception NB','EXCEPTION_NB')
,('9','Hold','Exception NB','EXCEPTION_NB')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('10','Transfer to DMC Reindex','Exception NB','EXCEPTION_NB')
,('11','Complete','Exception NB','EXCEPTION_NB')
,('12','Check Document Checklist','Client & Mandate','System')
,('13','Create Proposal','Check Document Checklist','System')
,('14','Send case to Billing Diversion','Create Proposal','System')
,('15','Send case to BRMS Verifier','Create Proposal','System')
,('16','Send Policy for Top Up ','Create Proposal','System')
,('17','Send case to Manual Data Entry','Create Proposal','System')
,('18','No Need Verifier','BRMS Pre-Verifier','System')
,('19','Need Verifier ','BRMS Pre-Verifier','System')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('20','Tele PMA','BRMS Verifier','System')
,('21','PMA ','BRMS Verifier','System')
,('22','Complete','Tele PMA','TELE_PMA')
,('23','Transfer to PMA','Tele PMA','TELE_PMA')
,('24','Hold','Tele PMA','TELE_PMA')
,('25','Pending Call','Tele PMA','TELE_PMA')
,('34','Send case to UW Scoring','Fraud Validation','System')
,('35','Facultative','UW Scoring','System')
,('36','Tele UW','UW Scoring','System')
,('37','Postpone','UW Scoring','System')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('38','Decline','UW Scoring','System')
,('39','Tele MNS','UW Scoring','System')
,('40','Non Jet','UW Scoring','System')
,('41','Jet','UW Scoring','System')
,('42','Standard','Underwriting Workflow','System')
,('43','Borderline Standard','Underwriting Workflow','System')
,('44','Substandard','Underwriting Workflow','System')
,('47','Transfer to Manual Data Entry','Underwriting Workflow','System')
,('48','Already WD/PO/DC/','Underwriting Workflow','System')
,('49','Postpone','Underwriting Workflow','System')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('50','Decline','Underwriting Workflow','System')
,('51','Withdrawn','Underwriting Workflow','System')
,('53','Transfer to Manual Data Entry','Policy Issuance Workflow','System')
,('54','Transfer to UW Admin','Policy Issuance Workflow','System')
,('55','Already WD/PO/DC/','Policy Issuance Workflow','System')
,('56','Postpone','Policy Issuance Workflow','System')
,('57','Decline','Policy Issuance Workflow','System')
,('58','Withdrawn','Policy Issuance Workflow','System')
,('59','Standard','Tele UW','TELE_UW')
,('60','Borderline Standard','Tele UW','TELE_UW')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('61','Substandard','Tele UW','TELE_UW')
,('62','Postpone','Tele UW','TELE_UW')
,('63','Decline','Tele UW','TELE_UW')
,('64','Withdrawn','Tele UW','TELE_UW')
,('65','Suspend','Tele UW','TELE_UW')
,('66','Re-verify','Tele UW','TELE_UW')
,('67','Already Inforced','Tele UW','TELE_UW')
,('68','Already WD/PO/DC','Tele UW','TELE_UW')
,('69','Hold','Tele UW','TELE_UW')
,('70','Transfer To UW Role','Tele UW','TELE_UW')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('71','Transfer to COORD Team','Tele UW','TELE_UW')
,('72','Transfer to SPV Team','Tele UW','TELE_UW')
,('73','Transfer to UWHD Team','Tele UW','TELE_UW')
,('74','Transfer to Tele UW Team','Tele UW','TELE_UW')
,('75','Transfer to UW ADMIN','Tele UW','TELE_UW')
,('76','Transfer to MLPO UW','Tele UW','TELE_UW')
,('77','Transfer to COO UW','Tele UW','TELE_UW')
,('78','Transfer to Data Entry','Tele UW','TELE_UW')
,('79','Transfer to Medical Officer','Tele UW','TELE_UW')
,('80','Transfer to OSC','Tele UW','TELE_UW')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('81','Transfer to Customer Care','Tele UW','TELE_UW')
,('82','Transfer to Call Panel','Tele UW','TELE_UW')
,('83','Transfer to Tele MNS','Tele UW','TELE_UW')
,('84','Transfer to Reinsurer','Tele UW','TELE_UW')
,('85','Pending Call','Tele UW','TELE_UW')
,('86','Back to User','Tele UW','TELE_UW')
,('87','Decline','Tele MNS','TELE_MNS')
,('88','Pending Call','Tele MNS','TELE_MNS')
,('89','Hold','Tele MNS','TELE_MNS')
,('90','Transfer to OSC Handler','Tele MNS','TELE_MNS')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('91','Transfer to UW Non Reguler ','Tele MNS','TELE_MNS')
,('92','Transfer to UW Regular','Tele MNS','TELE_MNS')
,('93','Standard','Underwriting','UW')
,('26','Transfer to PMA Coord','Data Verifier','NB_PMA')
,('27','Transfer to Data Entry','Data Verifier','NB_PMA')
,('28','Complete','Data Verifier','NB_PMA')
,('46','Re-verify','Underwriting Workflow','System')
,('29','Re-verify','Data Verifier','NB_PMA')
,('45','Already Inforced','Underwriting Workflow','System')
,('151','Hold','Q UW','Q_UW')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('119','Standard','Underwriting','COORD_UW')
,('120','Borderline Standard','Underwriting','COORD_UW')
,('199','Approve With POI','MLPO UW','MLPO_UW')
,('200','Approve Without POI','MLPO UW','MLPO_UW')
,('202','Need POI','MLPO UW','MLPO_UW')
,('205','Approve With POI','COO UW','COO_UW')
,('206','Approve Without POI','COO UW','COO_UW')
,('208','Need POI','COO UW','COO_UW')
,('211','Fraud Validation','Check Payment','System')
,('212','Exception Acceptance','Check Payment','System')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('213','Check Payment 2 ','Check Payment','System')
,('214','Check Payment','Check Payment 2','System')
,('215','Exception Acceptance','Check Payment 2','System')
,('216','Transfer to Exception UW','Exception Acceptance','EXCEPTION_ACCPT')
,('217','Suspend','Exception Acceptance','EXCEPTION_ACCPT')
,('219','Hold','Exception Acceptance','EXCEPTION_ACCPT')
,('221','EXCEPTION_UW','UW Scoring','System')
,('222','Issuance Policy Life Asia','UW Scoring','System')
,('223','QCV Roles','Issuance Policy Life Asia','System')
,('224','Done','Issuance Policy Life Asia','System')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('225','Suspend','Rejection Group','UW_ADMIN')
,('226','Transfer to NTU Reopen','Rejection Group','UW_ADMIN')
,('227','Transfer to DMC Reindex','Rejection Group','UW_ADMIN')
,('228','Hold','Rejection Group','UW_ADMIN')
,('229','Back to User ','Rejection Group','UW_ADMIN')
,('230','Reinsurance Support','Issuance Policy Life Asia','System')
,('231','Top Up Checker','Issuance Policy Life Asia','System')
,('233','Standard','Exception UW','EXCEPTION_UW')
,('234','Borderline Standard','Exception UW','EXCEPTION_UW')
,('235','Substandard','Exception UW','EXCEPTION_UW')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('236','Postpone','Exception UW','EXCEPTION_UW')
,('237','Decline','Exception UW','EXCEPTION_UW')
,('238','Withdrawn','Exception UW','EXCEPTION_UW')
,('239','Suspend','Exception UW','EXCEPTION_UW')
,('240','Re-verify','Exception UW','EXCEPTION_UW')
,('241','Already Inforced','Exception UW','EXCEPTION_UW')
,('242','Already WD/PO/DC','Exception UW','EXCEPTION_UW')
,('243','Hold','Exception UW','EXCEPTION_UW')
,('244','Transfer To Exception UW ','Exception UW','EXCEPTION_UW')
,('245','Transfer to UW ADMIN','Exception UW','EXCEPTION_UW')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('246','Transfer to Tele UW','Exception UW','EXCEPTION_UW')
,('247','Transfer to MLPO UW','Exception UW','EXCEPTION_UW')
,('248','Transfer to COO UW','Exception UW','EXCEPTION_UW')
,('249','Transfer to Data Entry','Exception UW','EXCEPTION_UW')
,('250','Transfer to Medical Officer','Exception UW','EXCEPTION_UW')
,('251','Transfer to OSC','Exception UW','EXCEPTION_UW')
,('252','Transfer to Customer Care','Exception UW','EXCEPTION_UW')
,('253','Transfer to Call Panel','Exception UW','EXCEPTION_UW')
,('254','Transfer to Tele MNS','Exception UW','EXCEPTION_UW')
,('255','Reindex','DMC Reindex','DMC_REINDEX')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('256','Hold','DMC Reindex','DMC_REINDEX')
,('257','Reject','DMC Reindex','DMC_REINDEX')
,('260','Accept','NTU Reopen','NTU_REOPEN')
,('261','Hold','NTU Reopen','NTU_REOPEN')
,('262','Reject','NTU Reopen','NTU_REOPEN')
,('263','Transfer to UW Admin','NTU Reopen','NTU_REOPEN')
,('264','Transfer to Medical Officer','NTU Reopen','NTU_REOPEN')
,('265','Transfer to Call Panel','NTU Reopen','NTU_REOPEN')
,('266','Transfer to Customer Care','NTU Reopen','NTU_REOPEN')
,('267','Hold','Billing Refund','BILLING_REFUND')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('268','Complete','Billing Refund','BILLING_REFUND')
,('269','Need Revision ','Medical Officer','MEDICAL_OFFICER')
,('270','Already Correct','Medical Officer','MEDICAL_OFFICER')
,('272','Transfer to Policy Correction','QCV','QUALITY_CONTROL')
,('273','Hold','Medical Officer','MEDICAL_OFFICER')
,('276','Back to User ','Customer Care','CUST_CARE')
,('277','HARD_TO_CONTACT','Customer Care','CUST_CARE')
,('278','Credible ','OSC Handler','OSC_HANDLER')
,('279','Not Credible','OSC Handler','OSC_HANDLER')
,('280','Contactable','OSC Handler','OSC_HANDLER')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('281','Not Contactable','OSC Handler','OSC_HANDLER')
,('282','Hold','OSC Handler','OSC_HANDLER')
,('283','Idle Task','OSC Handler','OSC_HANDLER')
,('201','Reject','MLPO UW','MLPO_UW')
,('207','Reject','COO UW','COO_UW')
,('203','Back To User','MLPO UW','MLPO_UW')
,('209','Back To User','COO UW','COO_UW')
,('204','Hold','MLPO UW','MLPO_UW')
,('210','Hold','COO UW','COO_UW')
,('232','Hold','QCV','QUALITY_CONTROL')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('218','Already Inforced','Exception Acceptance','EXCEPTION_ACCPT')
,('271','Need Requirement','QCV','QUALITY_CONTROL')
,('274','Temp Suspend','Customer Care','CUST_CARE')
,('284','Temp Suspend','Call Panel','CALL_PANEL')
,('275','1 Day Suspend','Customer Care','CUST_CARE')
,('286','Back to User','Call Panel','CALL_PANEL')
,('287','Hold','Call Panel','CALL_PANEL')
,('294','Accept','NB Afterissued','NB_AFTERISSUED')
,('295','Hold','NB Afterissued','NB_AFTERISSUED')
,('296','Reject','NB Afterissued','NB_AFTERISSUED')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('297','Transfer to PHS Dochandler','NB Afterissued','NB_AFTERISSUED')
,('298','Transfer to Claim Dochandler','NB Afterissued','NB_AFTERISSUED')
,('299','Transfer to Billing Dochandler','NB Afterissued','NB_AFTERISSUED')
,('300','Transfer to NB Policy Correction','NB Afterissued','NB_AFTERISSUED')
,('301','Complete','PHS Dochandler','PHS_DOCHANDLER')
,('302','Hold','PHS Dochandler','PHS_DOCHANDLER')
,('304','Complete','CLM Dochandler','CLM_DOCHANDLER')
,('305','Hold','CLM Dochandler','CLM_DOCHANDLER')
,('307','Complete','Billing Dochandler','BILLING_DOCHANDLER')
,('308','Hold','Billing Dochandler','BILLING_DOCHANDLER')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('309','Accept','Affiasseser','AFIASSESSER')
,('310','Hold','Affiasseser','AFIASSESSER')
,('311','Reject','Affiasseser','AFIASSESSER')
,('312','Complete','NB Policy Correction','NB_POLICY_CORRECTION')
,('313','Hold','NB Policy Correction','NB_POLICY_CORRECTION')
,('314','Transfer to AFIASSESSER','NB Policy Correction','NB_POLICY_CORRECTION')
,('315','Back to User','NB Policy Correction','NB_POLICY_CORRECTION')
,('316','Accept ','Dochandler','DOCHANDLER')
,('317','Reject','Dochandler','DOCHANDLER')
,('318','Hold','Dochandler','DOCHANDLER')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('319','Transfer to DMC Reindex','Dochandler','DOCHANDLER')
,('320','Complete','Copy Medical','COPY_MEDICAL')
,('321','Suspend','Copy Medical','COPY_MEDICAL')
,('322','Transfer to DMC Reindex','Copy Medical','COPY_MEDICAL')
,('323','Hold','Copy Medical','COPY_MEDICAL')
,('325','Complete','Exception Copy Medical','EXCEPTION_COPY_MEDICAL')
,('326','Hold','Exception Copy Medical','EXCEPTION_COPY_MEDICAL')
,('327','Complete','Unidentified Document','UNIDENTIFIED_DOCUMENT')
,('328','Hold','Unidentified Document','UNIDENTIFIED_DOCUMENT')
,('329','Transfer to DMC Reindex','Unidentified Document','UNIDENTIFIED_DOCUMENT')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('330','Complete','Reinsurance Support','REINSURANCE_SUPPORT')
,('331','Transfer to DMC Reindex','Reinsurance Support','REINSURANCE_SUPPORT')
,('332','Hold','Reinsurance Support','REINSURANCE_SUPPORT')
,('333','Complete','Tele KSL','TELE_KSL')
,('334','Decline','Tele KSL','TELE_KSL')
,('335','Pending Call','Tele KSL','TELE_KSL')
,('336','Hold','Tele KSL','TELE_KSL')
,('337','Transfer to OSC Handler','Tele KSL','TELE_KSL')
,('342','Complete','QA STP','QA_STP')
,('343','Hold','QA STP','QA_STP')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('344','Refer to Q CC','QA STP','QA_STP')
,('345','Accept','Q CC','Q_CC')
,('346','Back to User','Q CC','Q_CC')
,('347','Hold','Q CC','Q_CC')
,('348','Complete','QA PMA UW','QA_PMA_UW')
,('349','Finding BRMS','QA PMA UW','QA_PMA_UW')
,('350','Suggestion for BRMS','QA PMA UW','QA_PMA_UW')
,('351','Hold','QA PMA UW','QA_PMA_UW')
,('352','Refer to Q UW','QA PMA UW','QA_PMA_UW')
,('353','Refer to Q PMA','QA PMA UW','QA_PMA_UW')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('354','Refer to Q UW Admin','QA PMA UW','QA_PMA_UW')
,('355','Refer to Q Tele UW','QA PMA UW','QA_PMA_UW')
,('356','Refer to QA PMA UW','QA PMA UW','QA_PMA_UW')
,('357','Refer to Q PC','QA PMA UW','QA_PMA_UW')
,('358','Accept','Q PMA','Q_PMA')
,('359','Back to User','Q PMA','Q_PMA')
,('360','Hold','Q PMA','Q_PMA')
,('361','Accept','Q UW','Q_UW')
,('362','Back to User','Q UW','Q_UW')
,('363','Accept','Q UW Admin','Q_UW_ADMIN')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('364','Back to User','Q UW Admin','Q_UW_ADMIN')
,('365','Hold','Q UW Admin','Q_UW_ADMIN')
,('366','Accept','Q Tele UW','Q_TELE_UW')
,('367','Back to User','Q Tele UW','Q_TELE_UW')
,('368','Hold','Q Tele UW','Q_TELE_UW')
,('369','Accept','Q PC','Q_PC')
,('370','Back to User','Q PC','Q_PC')
,('371','Hold','Q PC','Q_PC')
,('372','Transfer to User ','Exception Block','ADMINISTRATOR')
,('373','Terminate','Exception Block','ADMINISTRATOR')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('374','Resume','Exception Block','ADMINISTRATOR')
,('375','Transfer to Pooling','Exception Block','ADMINISTRATOR')
,('376','Complete','PHS Topup','PHS_TOPUP')
,('377','Hold','PHS Topup','PHS_TOPUP')
,('378','Duplicate','Check Duplicate','System')
,('379','Not Duplicate','Check Duplicate','System')
,('385','Pending Top Up','Check Policy Status','System')
,('386','to Create Top Up to LAS','Check Policy Status','System')
,('387','Exception Top Up','Check Policy Status','System')
,('388','Exception Top Up','Pending Top Up','System')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('389','Create Top Up to LAS','Pending Top Up','System')
,('390','Exception Top Up','Pending Top Up','System')
,('391','Fraud Validation','Create Top Up To LAS','System')
,('392','Exeception Top Up','Create Top Up To LAS','System')
,('324','Temp Suspend','Exception Copy Medical','EXCEPTION_COPY_MEDICAL')
,('285','1 Day Suspend','Call Panel','CALL_PANEL')
,('288','Complete','Topup Checker','TOPUP_CHECKER')
,('289','Reject','Topup Checker','TOPUP_CHECKER')
,('290','Hold','Topup Checker','TOPUP_CHECKER')
,('291','Suspend','Topup Checker','TOPUP_CHECKER')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('292','Transfer to DMC Reindex','Topup Checker','TOPUP_CHECKER')
,('293','Transfer to PHS Topup','Topup Checker','TOPUP_CHECKER')
,('303','Transfer to NB Afterissued','PHS Dochandler','PHS_DOCHANDLER')
,('306','Transfer to NB Afterissued','CLM Dochandler','CLM_DOCHANDLER')
,('393','Waiting for Activation','Fraud Validation','System')
,('394','MLPO Top Up','Fraud Validation','System')
,('395','Approve With POI','MLPO Top Up','MLPO_TOPUP')
,('396','Approve Without POI','MLPO Top Up','MLPO_TOPUP')
,('397','Reject','MLPO Top Up','MLPO_TOPUP')
,('398','Need POI','MLPO Top Up','MLPO_TOPUP')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('399','Back to User','MLPO Top Up','MLPO_TOPUP')
,('400','Hold','MLPO Top Up','MLPO_TOPUP')
,('415','Terminate case from workflow','Waiting For Activation','System')
,('417','Complete','Exception Top Up','EXCEPTION_TOPUP')
,('418','Hold','Exception Top Up','EXCEPTION_TOPUP')
,('419','Transfer to DMC Reindex','Exception Top Up','EXCEPTION_TOPUP')
,('420','Transfer to NB Top Up','Exception Top Up','EXCEPTION_TOPUP')
,('421','Complete','Rejection Group','UW_ADMIN')
,('-1','    ',NULL,NULL)
,('258','Hold','Billing Diversion','BILLING_DIVERSION')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('259','Complete','Billing Diversion','BILLING_DIVERSION')
,('416','Complete','QCV','QUALITY_CONTROL')
,('401','Approve ','Top Up Decision','NB_TOPUP_DECISION')
,('402','Reject','Top Up Decision','NB_TOPUP_DECISION')
,('403','Hold','Top Up Decision','NB_TOPUP_DECISION')
,('404','Suspend','Top Up Decision','NB_TOPUP_DECISION')
,('405','Transfer to NB Top Up','Top Up Decision','NB_TOPUP_DECISION')
,('406','Transfer to PHS Topup','Top Up Decision','NB_TOPUP_DECISION')
,('407','Transfer to MLPO Top Up','Top Up Decision','NB_TOPUP_DECISION')
,('408','Transfer to COO','Top Up Decision','NB_TOPUP_DECISION')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('380','Complete','Top Up Data Entry','NB_TOPUP_ENTRY')
,('381','Hold','Top Up Data Entry','NB_TOPUP_ENTRY')
,('382','Suspend','Top Up Data Entry','NB_TOPUP_ENTRY')
,('383','Transfer to NB Top Up','Top Up Data Entry','NB_TOPUP_ENTRY')
,('384','Transfer to PHS Topup','Top Up Data Entry','NB_TOPUP_ENTRY')
,('338','Suspend','Reinsurer','REASS_ADMIN')
,('339','Back To User','Reinsurer','REASS_ADMIN')
,('340','Hold','Reinsurer','REASS_ADMIN')
,('341','Transfer To UW Role','Reinsurer','REASS_ADMIN')
,('30','Back To User','Data Verifier','NB_PMA_COORD')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('31','Hold','Data Verifier','NB_PMA_COORD')
,('32','Complete','Data Verifier','NB_PMA_COORD')
,('33','Re-verify','Data Verifier','NB_PMA_COORD')
,('121','Substandard','Underwriting','COORD_UW')
,('122','Postpone','Underwriting','COORD_UW')
,('123','Decline','Underwriting','COORD_UW')
,('124','Withdrawn','Underwriting','COORD_UW')
,('125','Suspend','Underwriting','COORD_UW')
,('126','Re-verify','Underwriting','COORD_UW')
,('127','Already Inforced','Underwriting','COORD_UW')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('128','Already WD/PO/DC','Underwriting','COORD_UW')
,('129','Hold','Underwriting','COORD_UW')
,('130','Transfer To UW Role','Underwriting','COORD_UW')
,('131','Transfer to COORD Team','Underwriting','COORD_UW')
,('132','Transfer to SPV Team','Underwriting','COORD_UW')
,('133','Transfer to UWHD Team','Underwriting','COORD_UW')
,('134','Transfer to Tele UW Team','Underwriting','COORD_UW')
,('135','Transfer to UW ADMIN','Underwriting','COORD_UW')
,('94','Borderline Standard','Underwriting','UW')
,('95','Substandard','Underwriting','UW')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('96','Postpone','Underwriting','UW')
,('97','Decline','Underwriting','UW')
,('98','Withdrawn','Underwriting','UW')
,('99','Suspend','Underwriting','UW')
,('100','Re-verify','Underwriting','UW')
,('101','Already Inforced','Underwriting','UW')
,('102','Already WD/PO/DC','Underwriting','UW')
,('103','Hold','Underwriting','UW')
,('104','Transfer To UW Role','Underwriting','UW')
,('105','Transfer to COORD Team','Underwriting','UW')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('106','Transfer to SPV Team','Underwriting','UW')
,('107','Transfer to UWHD Team','Underwriting','UW')
,('108','Transfer to Tele UW Team','Underwriting','UW')
,('109','Transfer to UW ADMIN','Underwriting','UW')
,('110','Transfer to MLPO UW','Underwriting','UW')
,('111','Transfer to COO UW','Underwriting','UW')
,('112','Transfer to Data Entry','Underwriting','UW')
,('113','Transfer to Medical Officer','Underwriting','UW')
,('114','Transfer to OSC','Underwriting','UW')
,('115','Transfer to Customer Care','Underwriting','UW')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('116','Transfer to Call Panel','Underwriting','UW')
,('117','Transfer to Tele MNS','Underwriting','UW')
,('118','Transfer to Reinsurer','Underwriting','UW')
,('422','Unhold','Hold (DE)','NB_DE')
,('423','Unhold','Hold (Exception NB)','EXCEPTION_NB')
,('424','Unhold','Hold (Tele PMA)','TELE_PMA')
,('426','Unhold','Hold (Tele UW)','TELE_UW')
,('428','Unhold','Hold (Tele MNS)','TELE_MNS')
,('434','Unhold','Hold (Q UW)','Q_UW')
,('437','Unhold','Hold (MLPO UW)','MLPO_UW')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('438','Unhold','Hold (COO UW)','COO_UW')
,('439','Unhold','Hold (Exception Acceptance)','EXCEPTION_ACCPT')
,('440','Unhold','Hold (Rejection Group)','UW_ADMIN')
,('441','Unhold','Hold (QCV)','QUALITY_CONTROL')
,('442','Unhold','Hold (Exception UW)','EXCEPTION_UW')
,('443','Unhold','Hold (DMC Reindex)','DMC_REINDEX')
,('444','Unhold','Hold (Billing Diversion)','BILLING_DIVERSION')
,('445','Unhold','Hold (NTU Reopen)','NTU_REOPEN')
,('446','Unhold','Hold (Billing Refund)','BILLING_REFUND')
,('447','Unhold','Hold (Medical Officer)','MEDICAL_OFFICER')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('448','Unhold','Hold (OSC Handler)','OSC_HANDLER')
,('449','Unhold','Hold (Call Panel)','CALL_PANEL')
,('451','Unhold','Hold (NB Afterissued)','NB_AFTERISSUED')
,('452','Unhold','Hold (PHS Dochandler)','PHS_DOCHANDLER')
,('453','Unhold','Hold (CLM Dochandler)','CLM_DOCHANDLER')
,('454','Unhold','Hold (Billing Dochandler)','BILLING_DOCHANDLER')
,('455','Unhold','Hold (Affiasseser)','AFIASSESSER')
,('456','Unhold','Hold (NB Policy Correction)','NB_POLICY_CORRECTION')
,('457','Unhold','Hold (Dochandler)','DOCHANDLER')
,('458','Unhold','Hold (Copy Medical)','COPY_MEDICAL')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('459','Unhold','Hold (Exception Copy Medical)','EXCEPTION_COPY_MEDICAL')
,('460','Unhold','Hold (Unidentified Document)','UNIDENTIFIED_DOCUMENT')
,('461','Unhold','Hold (Reinsurance Support)','REINSURANCE_SUPPORT')
,('462','Unhold','Hold (Tele KSL)','TELE_KSL')
,('463','Unhold','Hold (Reinsurer)','REASS_ADMIN')
,('464','Unhold','Hold (QA STP)','QA_STP')
,('465','Unhold','Hold (Q CC)','Q_CC')
,('466','Unhold','Hold (QA PMA UQ)','QA_PMA_UW')
,('467','Unhold','Hold (Q PMA)','Q_PMA')
,('468','Unhold','Hold (Q UW Admin)','Q_UW_ADMIN')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('469','Unhold','Hold (Q Tele UW)','Q_TELE_UW')
,('470','Unhold','Hold (Q PC)','Q_PC')
,('471','Force Restart','Exception Block','ADMINISTRATOR')
,('472','Force Finish','Exception Block','ADMINISTRATOR')
,('473','Unhold','Hold (PHS Topup)','PHS_TOPUP')
,('474','Unhold','Hold (Top Up Data Entry)','NB_TOPUP_ENTRY')
,('427','Unhold','Hold (MLPO Top Up)','MLPO_TOPUP')
,('429','Unhold','Hold (Top Up Decision)','NB_TOPUP_DECISION')
,('433','Transfer to DMC Reindex','Exception Top Up','EXCEPTION_TOPUP')
,('436','Finish Issued','Issuance Policy LifeAsia','System')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('425','Unhold','Data Verifier','NB_PMA_COORD')
,('136','Transfer to MLPO UW','Underwriting','COORD_UW')
,('137','Transfer to COO UW','Underwriting','COORD_UW')
,('138','Transfer to Data Entry','Underwriting','COORD_UW')
,('139','Transfer to Medical Officer','Underwriting','COORD_UW')
,('140','Transfer to OSC','Underwriting','COORD_UW')
,('141','Transfer to Customer Care','Underwriting','COORD_UW')
,('142','Transfer to Call Panel','Underwriting','COORD_UW')
,('143','Transfer to Tele MNS','Underwriting','COORD_UW')
,('144','Transfer to Reinsurer','Underwriting','COORD_UW')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('430','Unhold','Underwriting','COORD_UW')
,('165','Transfer to Data Entry','Underwriting','SPV_UW')
,('145','Standard','Underwriting','SPV_UW')
,('146','Borderline Standard','Underwriting','SPV_UW')
,('147','Substandard','Underwriting','SPV_UW')
,('148','Postpone','Underwriting','SPV_UW')
,('149','Decline','Underwriting','SPV_UW')
,('150','Withdrawn','Underwriting','SPV_UW')
,('152','Suspend','Underwriting','SPV_UW')
,('153','Re-verify','Underwriting','SPV_UW')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('154','Already Inforced','Underwriting','SPV_UW')
,('155','Already WD/PO/DC','Underwriting','SPV_UW')
,('156','Hold','Underwriting','SPV_UW')
,('157','Transfer To UW Role','Underwriting','SPV_UW')
,('158','Transfer to COORD Team','Underwriting','SPV_UW')
,('159','Transfer to SPV Team','Underwriting','SPV_UW')
,('160','Transfer to UWHD Team','Underwriting','SPV_UW')
,('161','Transfer to Tele UW Team','Underwriting','SPV_UW')
,('162','Transfer to UW ADMIN','Underwriting','SPV_UW')
,('163','Transfer to MLPO UW','Underwriting','SPV_UW')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('164','Transfer to COO UW','Underwriting','SPV_UW')
,('167','Transfer to Medical Officer','Underwriting','SPV_UW')
,('168','Transfer to OSC','Underwriting','SPV_UW')
,('169','Transfer to Customer Care','Underwriting','SPV_UW')
,('170','Transfer to Call Panel','Underwriting','SPV_UW')
,('171','Transfer to Tele MNS','Underwriting','SPV_UW')
,('172','Transfer to Reinsurer','Underwriting','SPV_UW')
,('432','Unhold','Underwriting','SPV_UW')
,('178','Withdrawn','Underwriting','UWHD_TEAM')
,('173','Standard','Underwriting','UWHD_TEAM')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('174','Borderline Standard','Underwriting','UWHD_TEAM')
,('175','Substandard','Underwriting','UWHD_TEAM')
,('176','Postpone','Underwriting','UWHD_TEAM')
,('177','Decline','Underwriting','UWHD_TEAM')
,('179','Suspend','Underwriting','UWHD_TEAM')
,('180','Re-verify','Underwriting','UWHD_TEAM')
,('181','Already Inforced','Underwriting','UWHD_TEAM')
,('182','Already WD/PO/DC','Underwriting','UWHD_TEAM')
,('183','Hold','Underwriting','UWHD_TEAM')
,('184','Transfer To UW Role','Underwriting','UWHD_TEAM')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('185','Transfer to COORD Team','Underwriting','UWHD_TEAM')
,('186','Transfer to SPV Team','Underwriting','UWHD_TEAM')
,('187','Transfer to UWHD Team','Underwriting','UWHD_TEAM')
,('188','Transfer to Tele UW Team','Underwriting','UWHD_TEAM')
,('189','Transfer to UW ADMIN','Underwriting','UWHD_TEAM')
,('190','Transfer to MLPO UW','Underwriting','UWHD_TEAM')
,('191','Transfer to COO UW','Underwriting','UWHD_TEAM')
,('192','Transfer to Data Entry','Underwriting','UWHD_TEAM')
,('193','Transfer to Medical Officer','Underwriting','UWHD_TEAM')
,('194','Transfer to OSC','Underwriting','UWHD_TEAM')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('195','Transfer to Customer Care','Underwriting','UWHD_TEAM')
,('196','Transfer to Call Panel','Underwriting','UWHD_TEAM')
,('197','Transfer to Tele MNS','Underwriting','UWHD_TEAM')
,('198','Transfer to Reinsurer','Underwriting','UWHD_TEAM')
,('435','Unhold','Underwriting','UWHD_TEAM')
,('450','Unhold','Topup Checker','TOPUP_CHECKER')
,('409','Approve With POI','COO Top Up','COO_TOPUP')
,('410','Approve Without POI','COO Top Up','COO_TOPUP')
,('411','Reject','COO Top Up','COO_TOPUP')
,('412','Need POI','COO Top Up','COO_TOPUP')
;
INSERT INTO wfstatus."MsWfStatus" ("WfCd","WfStatus","WfActivity","WfRole") VALUES 
('413','Back to User','COO Top Up','COO_TOPUP')
,('414','Hold','COO Top Up','COO_TOPUP')
,('431','Unhold','COO Top Up','COO_TOPUP')
;