INSERT INTO pd_dsg."XmlTemplate" ("XmlTemplateId", "TagXml", "Value", "Level", "Sequence", "ParentId", "IsDelete", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "ProductCd", "IsArray", "TagType", "SeparatorValue") VALUES ('xmlTemplateSKA', 'ska_form', 'getPolicy.getSka', 1, 11, 'root', false, 'prufast_admin', now(), 'prufast_admin', now(), 'pd01', false, 'json', '');

INSERT INTO pd_dsg."XmlTemplate" ("XmlTemplateId", "TagXml", "Value", "Level", "Sequence", "ParentId", "IsDelete", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "ProductCd", "IsArray", "TagType", "SeparatorValue") VALUES ('xmlTemplateSKADocId', 'skadoc_id', 'getPolicy.getSka.getDoc_id', 2, 1, 'xmlTemplateSKA', false, 'prufast_admin', now(), 'prufast_admin', now(), 'pd01', false, 'json', '');
INSERT INTO pd_dsg."XmlTemplate" ("XmlTemplateId", "TagXml", "Value", "Level", "Sequence", "ParentId", "IsDelete", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "ProductCd", "IsArray", "TagType", "SeparatorValue") VALUES ('xmlTemplateSKAFlagLoosemail', 'skaloosemail_flag', 'getPolicy.getSka.getSkaloosemail_flag', 2, 1, 'xmlTemplateSKA', false, 'prufast_admin', now(), 'prufast_admin', now(), 'pd01', false, 'json', '');
INSERT INTO pd_dsg."XmlTemplate" ("XmlTemplateId", "TagXml", "Value", "Level", "Sequence", "ParentId", "IsDelete", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "ProductCd", "IsArray", "TagType", "SeparatorValue") VALUES ('xmlTemplateSKAPhName', 'skaphname', 'getPolicy.getSka.getPhName', 2, 2, 'xmlTemplateSKA', false, 'prufast_admin', now(), 'prufast_admin', now(), 'pd01', false, 'json', '');
INSERT INTO pd_dsg."XmlTemplate" ("XmlTemplateId", "TagXml", "Value", "Level", "Sequence", "ParentId", "IsDelete", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "ProductCd", "IsArray", "TagType", "SeparatorValue") VALUES ('xmlTemplateSKAPhDob', 'skaphdob', 'getPolicy.getSka.getPhDob', 2, 3, 'xmlTemplateSKA', false, 'prufast_admin', now(), 'prufast_admin', now(), 'pd01', false, 'json', '');
INSERT INTO pd_dsg."XmlTemplate" ("XmlTemplateId", "TagXml", "Value", "Level", "Sequence", "ParentId", "IsDelete", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "ProductCd", "IsArray", "TagType", "SeparatorValue") VALUES ('xmlTemplateSKALifeAssName', 'skalifesssname', 'getPolicy.getSka.getTuName', 2, 4, 'xmlTemplateSKA', false, 'prufast_admin', now(), 'prufast_admin', now(), 'pd01', false, 'json', '');
INSERT INTO pd_dsg."XmlTemplate" ("XmlTemplateId", "TagXml", "Value", "Level", "Sequence", "ParentId", "IsDelete", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "ProductCd", "IsArray", "TagType", "SeparatorValue") VALUES ('xmlTemplateSKALifeAssDob', 'skalifeasspdob', 'getPolicy.getSka.getTuDob', 2, 5, 'xmlTemplateSKA', false, 'prufast_admin', now(), 'prufast_admin', now(), 'pd01', false, 'json', '');
INSERT INTO pd_dsg."XmlTemplate" ("XmlTemplateId", "TagXml", "Value", "Level", "Sequence", "ParentId", "IsDelete", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "ProductCd", "IsArray", "TagType", "SeparatorValue") VALUES ('xmlTemplateSKALifeAssRelation', 'skalifeassrelation', 'getPolicy.getSka.getTuRelation', 2, 6, 'xmlTemplateSKA', false, 'prufast_admin', now(), 'prufast_admin', now(), 'pd01', false, 'json', '');

INSERT INTO pd_dsg."XmlTemplate" ("XmlTemplateId", "TagXml", "Value", "Level", "Sequence", "ParentId", "IsDelete", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "ProductCd", "IsArray", "TagType", "SeparatorValue") VALUES ('xmlTemplateSKALifeAssRelationBenefs', 'skalifeassrelation_benefs', 'null', 2, 7, 'xmlTemplateSKA', false, 'prufast_admin', now(), 'prufast_admin', now(), 'pd01', false, 'json', '');
INSERT INTO pd_dsg."XmlTemplate" ("XmlTemplateId", "TagXml", "Value", "Level", "Sequence", "ParentId", "IsDelete", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "ProductCd", "IsArray", "TagType", "SeparatorValue") VALUES ('xmlTemplateSKALifeAssRelationBenef', 'skalifeassrelation_benef', 'getPolicy.getSka.getTuRelationBenefs', 3, 1, 'xmlTemplateSKALifeAssRelationBenefs', false, 'prufast_admin', now(), 'prufast_admin', now(), 'pd01', true, 'array_string', '');

INSERT INTO pd_dsg."XmlTemplate" ("XmlTemplateId", "TagXml", "Value", "Level", "Sequence", "ParentId", "IsDelete", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "ProductCd", "IsArray", "TagType", "SeparatorValue") VALUES ('xmlTemplateSKAFlagA', 'skaflag_a', 'getPolicy.getSka.getFlagA', 2, 8, 'xmlTemplateSKA', false, 'prufast_admin', now(), 'prufast_admin', now(), 'pd01', false, 'json', '');
INSERT INTO pd_dsg."XmlTemplate" ("XmlTemplateId", "TagXml", "Value", "Level", "Sequence", "ParentId", "IsDelete", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "ProductCd", "IsArray", "TagType", "SeparatorValue") VALUES ('xmlTemplateSKAFlagB', 'skaflag_b', 'getPolicy.getSka.getFlagB', 2, 9, 'xmlTemplateSKA', false, 'prufast_admin', now(), 'prufast_admin', now(), 'pd01', false, 'json', '');
INSERT INTO pd_dsg."XmlTemplate" ("XmlTemplateId", "TagXml", "Value", "Level", "Sequence", "ParentId", "IsDelete", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "ProductCd", "IsArray", "TagType", "SeparatorValue") VALUES ('xmlTemplateSKAFlagC', 'skaflag_c', 'getPolicy.getSka.getFlagC', 2, 10, 'xmlTemplateSKA', false, 'prufast_admin', now(), 'prufast_admin', now(), 'pd01', false, 'json', '');
INSERT INTO pd_dsg."XmlTemplate" ("XmlTemplateId", "TagXml", "Value", "Level", "Sequence", "ParentId", "IsDelete", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "ProductCd", "IsArray", "TagType", "SeparatorValue") VALUES ('xmlTemplateSKAFlagD', 'skaflag_d', 'getPolicy.getSka.getFlagD', 2, 11, 'xmlTemplateSKA', false, 'prufast_admin', now(), 'prufast_admin', now(), 'pd01', false, 'json', '');
INSERT INTO pd_dsg."XmlTemplate" ("XmlTemplateId", "TagXml", "Value", "Level", "Sequence", "ParentId", "IsDelete", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "ProductCd", "IsArray", "TagType", "SeparatorValue") VALUES ('xmlTemplateSKAFlagE', 'skaflag_e', 'getPolicy.getSka.getFlagE.getValue', 2, 12, 'xmlTemplateSKA', false, 'prufast_admin', now(), 'prufast_admin', now(), 'pd01', false, 'json', '');
INSERT INTO pd_dsg."XmlTemplate" ("XmlTemplateId", "TagXml", "Value", "Level", "Sequence", "ParentId", "IsDelete", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "ProductCd", "IsArray", "TagType", "SeparatorValue") VALUES ('xmlTemplateSKADescE', 'skadesc_e', 'getPolicy.getSka.getFlagE.getDesc', 2, 13, 'xmlTemplateSKA', false, 'prufast_admin', now(), 'prufast_admin', now(), 'pd01', false, 'json', '');
INSERT INTO pd_dsg."XmlTemplate" ("XmlTemplateId", "TagXml", "Value", "Level", "Sequence", "ParentId", "IsDelete", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "ProductCd", "IsArray", "TagType", "SeparatorValue") VALUES ('xmlTemplateSKAFlagF', 'skaflag_f', 'getPolicy.getSka.getFlagF.getValue', 2, 14, 'xmlTemplateSKA', false, 'prufast_admin', now(), 'prufast_admin', now(), 'pd01', false, 'json', '');
INSERT INTO pd_dsg."XmlTemplate" ("XmlTemplateId", "TagXml", "Value", "Level", "Sequence", "ParentId", "IsDelete", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "ProductCd", "IsArray", "TagType", "SeparatorValue") VALUES ('xmlTemplateSKADescF', 'skadesc_f', 'getPolicy.getSka.getFlagF.getDesc', 2, 15, 'xmlTemplateSKA', false, 'prufast_admin', now(), 'prufast_admin', now(), 'pd01', false, 'json', '');

INSERT INTO pd_dsg."XmlTemplate" ("XmlTemplateId", "TagXml", "Value", "Level", "Sequence", "ParentId", "IsDelete", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "ProductCd", "IsArray", "TagType", "SeparatorValue") VALUES ('xmlTemplateSKASigns', 'skasigns', 'null', 2, 16, 'xmlTemplateSKA', false, 'prufast_admin', now(), 'prufast_admin', now(), 'pd01', false, 'json', '');
INSERT INTO pd_dsg."XmlTemplate" ("XmlTemplateId", "TagXml", "Value", "Level", "Sequence", "ParentId", "IsDelete", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "ProductCd", "IsArray", "TagType", "SeparatorValue") VALUES ('xmlTemplateSKASign', 'skasign', 'getPolicy.getSka.getSign', 3, 1, 'xmlTemplateSKASigns', false, 'prufast_admin', now(), 'prufast_admin', now(), 'pd01', true, 'json', '');
INSERT INTO pd_dsg."XmlTemplate" ("XmlTemplateId", "TagXml", "Value", "Level", "Sequence", "ParentId", "IsDelete", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "ProductCd", "IsArray", "TagType", "SeparatorValue") VALUES ('xmlTemplateSKASignLoc', 'skasignloc', 'getLoc', 4, 1, 'xmlTemplateSKASign', false, 'prufast_admin', now(), 'prufast_admin', now(), 'pd01', false, 'json', '');
INSERT INTO pd_dsg."XmlTemplate" ("XmlTemplateId", "TagXml", "Value", "Level", "Sequence", "ParentId", "IsDelete", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "ProductCd", "IsArray", "TagType", "SeparatorValue") VALUES ('xmlTemplateSKASignDate', 'skasigndate', 'getDate', 4, 2, 'xmlTemplateSKASign', false, 'prufast_admin', now(), 'prufast_admin', now(), 'pd01', false, 'json', '');
INSERT INTO pd_dsg."XmlTemplate" ("XmlTemplateId", "TagXml", "Value", "Level", "Sequence", "ParentId", "IsDelete", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "ProductCd", "IsArray", "TagType", "SeparatorValue") VALUES ('xmlTemplateSKASignRole', 'skasignrole', 'getRole', 4, 3, 'xmlTemplateSKASign', false, 'prufast_admin', now(), 'prufast_admin', now(), 'pd01', false, 'json', '');
INSERT INTO pd_dsg."XmlTemplate" ("XmlTemplateId", "TagXml", "Value", "Level", "Sequence", "ParentId", "IsDelete", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "ProductCd", "IsArray", "TagType", "SeparatorValue") VALUES ('xmlTemplateSKASignValue', 'skasignvalue', 'getValue', 4, 4, 'xmlTemplateSKASign', false, 'prufast_admin', now(), 'prufast_admin', now(), 'pd01', false, 'json', '');
INSERT INTO pd_dsg."XmlTemplate" ("XmlTemplateId", "TagXml", "Value", "Level", "Sequence", "ParentId", "IsDelete", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "ProductCd", "IsArray", "TagType", "SeparatorValue") VALUES ('xmlTemplateSKASignName', 'skasignname', 'getName', 4, 5, 'xmlTemplateSKASign', false, 'prufast_admin', now(), 'prufast_admin', now(), 'pd01', false, 'json', '');
INSERT INTO pd_dsg."XmlTemplate" ("XmlTemplateId", "TagXml", "Value", "Level", "Sequence", "ParentId", "IsDelete", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "ProductCd", "IsArray", "TagType", "SeparatorValue") VALUES ('xmlTemplateSKAVer', 'skaver', '0820', 2, 17, 'xmlTemplateSKA', false, 'prufast_admin', now(), 'prufast_admin', now(), 'pd01', false, 'constanta', '');